program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["--show-all-tests", "spec"]

expected_stdout = """
ðŸš€ Running 35 tests:
...................................

âœ… spec/aureum/cli/help.au.toml
âœ… spec/aureum/cli/no-args.au.toml
âœ… spec/aureum/cli/output-format.au.toml:summary-failing
âœ… spec/aureum/cli/output-format.au.toml:summary-passing
âœ… spec/aureum/cli/output-format.au.toml:tap-failing
âœ… spec/aureum/cli/output-format.au.toml:tap-passing
âœ… spec/aureum/cli/output-format.au.toml:unknown
âœ… spec/aureum/cli/run-tests-in-parallel.au.toml
âœ… spec/aureum/cli/show-all-tests.au.toml:default
âœ… spec/aureum/cli/show-all-tests.au.toml:show-all-tests
âœ… spec/aureum/cli/verbose.au.toml:default
âœ… spec/aureum/cli/verbose.au.toml:verbose-mode
âœ… spec/aureum/error/error.au.toml:empty-config
âœ… spec/aureum/error/error.au.toml:invalid-config
âœ… spec/aureum/error/error.au.toml:missing-config
âœ… spec/aureum/error/error.au.toml:missing-config-with-test-id
âœ… spec/aureum/error/error.au.toml:missing-env-var
âœ… spec/aureum/error/error.au.toml:missing-external-file
âœ… spec/aureum/error/error.au.toml:no-expectations
âœ… spec/aureum/error/error.au.toml:no-program-specified
âœ… spec/aureum/error/error.au.toml:unknown-test-program
âœ… spec/aureum/glob/absolute-path.au.toml
âœ… spec/aureum/glob/glob.au.toml:multiple-dirs
âœ… spec/aureum/glob/glob.au.toml:multiple-files
âœ… spec/aureum/glob/glob.au.toml:single-dir
âœ… spec/aureum/glob/glob.au.toml:single-file
âœ… spec/aureum/nested/missing-program.au.toml
âœ… spec/aureum/nested/two-levels.au.toml
âœ… spec/basic/description.au.toml - My description
âœ… spec/basic/expect-exit-code.au.toml
âœ… spec/basic/expect-stderr.au.toml
âœ… spec/basic/expect-stdout.au.toml
âœ… spec/basic/read-env-var.au.toml
âœ… spec/basic/read-external-file.au.toml
âœ… spec/basic/run-bash.au.toml

Test result: OK (35 passed, 0 failed)
"""
expected_stderr = ""
expected_status_code = 0
