test_program = { env = "AUREUM_EXEC" }
test_arguments = ["helpers/failing-test.toml"]

expected_stdout = """
âŒ ./helpers/failing-test.toml

Completed running 1 tests.
1 failures.
"""
expected_stderr = ""
expected_exit_code = 1
