program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["--show-all-tests", "helpers/missing-program.toml"]

expected_stdout = """
ğŸš€ Running 0 tests:


Test result: OK (0 passed, 0 failed)
"""
expected_stderr = """
ğŸ“‹ helpers/missing-program.toml
â””â”€ Validation errors
   â”œâ”€ test1
   â”‚  â””â”€ âŒ The field 'program' is required
   â””â”€ test2
      â””â”€ âŒ The field 'program' is required

Some config files contain errors (See above)
"""
expected_exit_code = 1
